### ISSUE TITLE
Slack rate limit

### ISSUE THREAD

**Issue by nolangormley** [dmytrotsko/fault-record-message-crawler#7]
This error should probably be handled by either 1) exiting and uploading what you have and storing the latest timestamp from the last post you got, or 2) sleeping until the ratelimit is gone. 

I prefer option 2 since it ensures that all get updated when chronicle runs this script

`Traceback (most recent call last):
  File "slack_scraper.py", line 77, in <module>
    main()
  File "slack_scraper.py", line 66, in main
    processed_messages, oldest_message_ts = process_conversation_history(conversation_history, client, channel_id, FAULT_RECORD_API_URL)
  File "/home/ngormley/fault-record-message-crawler/utils.py", line 343, in process_conversation_history
    replies = get_message_replies(
  File "/home/ngormley/fault-record-message-crawler/utils.py", line 145, in get_message_replies
    "author": get_user_id(get_user_info(client, reply["user"], True), fault_record_api_url),
  File "/home/ngormley/fault-record-message-crawler/utils.py", line 95, in get_user_info
    user_info = client.users_info(user=user_id)
  File "/home/ngormley/fault-record-message-crawler/pyenv/lib/python3.8/site-packages/slack/web/client.py", line 2206, in users_info
    return self.api_call("users.info", http_verb="GET", params=kwargs)
  File "/home/ngormley/fault-record-message-crawler/pyenv/lib/python3.8/site-packages/slack/web/base_client.py", line 150, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/home/ngormley/fault-record-message-crawler/pyenv/lib/python3.8/site-packages/slack/web/base_client.py", line 241, in _sync_send
    return self._urllib_api_call(
  File "/home/ngormley/fault-record-message-crawler/pyenv/lib/python3.8/site-packages/slack/web/base_client.py", line 369, in _urllib_api_call
    return SlackResponse(
  File "/home/ngormley/fault-record-message-crawler/pyenv/lib/python3.8/site-packages/slack/web/slack_response.py", line 194, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
`

**Comment by dmytrotsko** [comment]
Fixed with [retry](https://pypi.org/project/retry/) lib.
